Repository singhabahu/serverless-backend, pull requests merged in 2018-05, with the labels that each got.

#2 Add post confirmation trigger and code refactor
  .gitignore
  package-lock.json
  package.json
  serverless.yml
  src/cognito/post-confimation.js
  src/cognito/user-disable.trigger.js
  src/db/mysql-connector.js
  src/roles.js
  src/users.js
Labels: enhancement

#5 Resolve line break issue
  .eslintrc.yml
Labels: bug

#4 feature/mysql connector
  package-lock.json
  package.json
  serverless.yml
  src/db/models/organization.js
  src/db/models/role.js
  src/db/models/user.js
  src/db/mysql-connector.js
  webpack.config.js
Labels: enhancement

#7 Modify trigger to work with mySQL
  src/cognito/post-confimation.js
  src/db/models/organization.js
Labels: enhancement, fix

#9 Add project ORM model
  src/db/models/project.js
Labels: enhancement

#8 Feature/auth middleware
  package-lock.json
  package.json
  serverless.yml
  src/api/auth.js
Labels: enhancement

#10 Refactor get-all user API
  serverless.yml
  src/api/roles.js
  src/api/users.js
  src/db/models/user.js
  src/util/permission.js
Labels: enhancement
